### ISSUE TITLE
question

### ISSUE THREAD

**Issue by toshibochan** [geshafer/sharp_aquos_remote_control#2]
how to install on raspberry pi or mac?

**Comment by geshafer** [comment]
@toshibochan You can use [Ruby Gems](https://rubygems.org/pages/download) to install this gem.

[You can install Ruby Gems on your Raspberry Pi using APT](https://www.raspberrypi.org/documentation/linux/software/ruby.md):

```
sudo apt-get install rubygems
```

Once Ruby Gems is installed on your raspberry pi or mac you can use it to install this gem:

```
sudo gem install sharp_aquos_remote_control
```

I hope this helps! 😄
